// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ContextCheckpointDetails = { checkpointRef: string, generationId: string, turnRecordId: string, labels: Array<string>, stateEntryCount: number, windowNumber: bigint, firstWindowId: string, previousWindowId: string | null, windowId: string, };
