// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectAgentTaskPhase } from "./ProjectAgentTaskPhase";

export type ProjectAgentTask = { agentId: string, taskId: string, task: string, phase: ProjectAgentTaskPhase, sessionThreadId: string | null, parentThreadId: string, attempt: number, createdAt: bigint, updatedAt: bigint, };
