// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectTaskResultStatus } from "./ProjectTaskResultStatus";
import type { ProjectTaskSuggestedChild } from "./ProjectTaskSuggestedChild";

export type ProjectTaskResult = { status: ProjectTaskResultStatus, summary: string, artifacts: Array<string>, evidence: Array<string>, suggestedChildren: Array<ProjectTaskSuggestedChild>, error: string | null, completedAt: bigint, };
