// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectAgentTaskStatus } from "./ProjectAgentTaskStatus";

export type ProjectAgentPersistedResult = { status: ProjectAgentTaskStatus, agentId: string, taskId: string, result: string, artifacts: Array<string>, evidence: Array<string>, memoryCandidates: Array<string>, improvementProposals: Array<string>, error: string | null, };
