// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectAgentSession } from "./ProjectAgentSession";
import type { ProjectAgentTask } from "./ProjectAgentTask";

export type ProjectAgentRosterEntry = { id: string, description: string, enabled: boolean, activeSessionThreadId: string | null, session: ProjectAgentSession | null, currentTask: ProjectAgentTask | null, };
