// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProjectAgentDefinition = { id: string, description: string, enabled: boolean, definitionPath: string, constraintsFile: string, model: string | null, modelReasoningEffort: string | null, modelProvider: string | null, tools: Array<string>, memoryMaxItems: number, memoryMaxTokens: number, };
