// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectTaskEvaluation } from "./ProjectTaskEvaluation";
import type { ProjectTaskExecutor } from "./ProjectTaskExecutor";
import type { ProjectTaskResult } from "./ProjectTaskResult";
import type { ProjectTaskStatus } from "./ProjectTaskStatus";

export type ProjectTask = { taskId: string, parentTaskId: string | null, title: string, objective: string, requirements: Array<string>, status: ProjectTaskStatus, executor: ProjectTaskExecutor, executionTaskId: string | null, sessionThreadId: string | null, result: ProjectTaskResult | null, evaluation: ProjectTaskEvaluation | null, createdAt: bigint, updatedAt: bigint, };
