// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectAgentDefinition } from "./ProjectAgentDefinition";
import type { ProjectAgentPersistedResult } from "./ProjectAgentPersistedResult";
import type { ProjectAgentSession } from "./ProjectAgentSession";
import type { ProjectAgentTask } from "./ProjectAgentTask";

export type ThreadProjectAgentReadResponse = { projectRoot: string, agent: ProjectAgentDefinition, activeSessionThreadId: string | null, session: ProjectAgentSession | null, currentTask: ProjectAgentTask | null, currentResult: ProjectAgentPersistedResult | null, recentTasks: Array<ProjectAgentTask>, recentResults: Array<ProjectAgentPersistedResult>, };
