// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ThreadProjectAgentReadParams = { threadId: string, agentId: string,
/**
 * Optional recent-task and result count; the server applies a hard upper bound.
 */
taskLimit?: number | null, };
