// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectTaskExecutor } from "./ProjectTaskExecutor";

export type ThreadProjectTaskCreateParams = { threadId: string, parentTaskId?: string | null, title: string, objective: string, executor?: ProjectTaskExecutor | null, };
