// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectAgentRosterEntry } from "./ProjectAgentRosterEntry";

export type ThreadProjectAgentListResponse = { projectRoot: string, data: Array<ProjectAgentRosterEntry>, nextCursor: string | null, total: bigint, };
