// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectTaskResult } from "./ProjectTaskResult";

export type ThreadProjectTaskResultRecordParams = { threadId: string, taskId: string, result: ProjectTaskResult, };
