// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TurnResearchStateEntry } from "./TurnResearchStateEntry";

export type TurnResearchStateUpdatedNotification = { threadId: string, turnId: string, revision: bigint, changed: boolean, entries: Array<TurnResearchStateEntry>, };
