// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TurnResearchEntryKind } from "./TurnResearchEntryKind";
import type { TurnResearchScope } from "./TurnResearchScope";
import type { TurnResearchStatus } from "./TurnResearchStatus";

export type TurnResearchStateEntry = { id: string, scope: TurnResearchScope, kind: TurnResearchEntryKind, subject: string, statement: string, status: TurnResearchStatus, };
